eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: service-hi
#  cloud:
#    consul:
#      host: localhost
#      port: 8500
